name: Laravel Tests

on:
  pull_request:
  workflow_run:
    workflows: ["Trigger PR Update Checks"]
    types:
      - completed

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, ctype, iconv, sqlite3
          coverage: none
          ini-values: post_max_size=256M, upload_max_filesize=256M

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install NPM dependencies
        run: npm install

      - name: Build assets
        run: npm run build

      - name: Prepare environment
        run: |
          cp .env.example .env
          php artisan key:generate
          echo "DB_CONNECTION=sqlite" >> .env
          echo "DB_DATABASE=/tmp/database.sqlite" >> .env
          php artisan config:cache

      - name: Create SQLite Database
        run: |
          touch /tmp/database.sqlite

      - name: Directory Permissions
        run: sudo chmod -R 777 storage bootstrap/cache

      - name: Run Migrations
        run: php artisan migrate --force

      - name: Seed Database
        run: php artisan db:seed --force

      - name: Run Tests
        run: php artisan test --stop-on-failure

    env:
      APP_ENV: testing
      CACHE_DRIVER: array
      QUEUE_CONNECTION: sync
      SESSION_DRIVER: array
      DB_CONNECTION: sqlite
      DB_DATABASE: /tmp/database.sqlite
